### ISSUE TITLE
panic in handler GetRandomIdiom

### ISSUE THREAD

**Issue by llitfkitfk** [jqs7/zwei#4]
```
panic: invalid argument to Intn
zwei_1      |
zwei_1      | goroutine 1 [running]:
zwei_1      | math/rand.(*Rand).Intn(0xc0007ca900, 0x0, 0xc0000ab438)
zwei_1      |   /usr/local/go/src/math/rand/rand.go:169 +0x9c
zwei_1      | github.com/hanguofeng/gocaptcha.(*FontManager).GetRandomFont(0xc0007ca8a0, 0xc)
zwei_1      |   /go/pkg/mod/github.com/jqs7/gocaptcha@v1.0.8-0.20181014100812-c7bcbe23fde4/fontmanager.go:56 +0x3c
zwei_1      | github.com/hanguofeng/gocaptcha.(*CImage).DrawString(0xc0007d63b0, 0xc0007c6840, 0xc, 0x0)
zwei_1      |   /go/pkg/mod/github.com/jqs7/gocaptcha@v1.0.8-0.20181014100812-c7bcbe23fde4/cimage.go:74 +0x1e5
zwei_1      | github.com/jqs7/zwei/biz.Handler.GetRandomIdiom(0xc000058240, 0xc00000a200, 0x7ba0, 0x1, 0x0, 0x0)
zwei_1      |   /home/app/biz/handler.go:195 +0x19e
zwei_1      | github.com/jqs7/zwei/biz.Handler.NewMemberInGroup(0xc000058240, 0xc00000a200, 0x7ba0, 0xc000438280, 0xc0000b97a0, 0x225b9b79, 0xc0007f6508, 0x2, 0xc0007f650a, 0x5, ...)
zwei_1      |   /home/app/biz/handler.go:40 +0x116
zwei_1      | github.com/jqs7/zwei/bot/tg.Bot.onNewChatMembers(0xc000438280, 0x2acea69f, 0xc000779a38, 0x8, 0x0, 0x0, 0xc000779a50, 0xd, 0x0, 0x0, ...)
zwei_1      |   /home/app/bot/tg/bot.go:50 +0x16c
zwei_1      | github.com/jqs7/zwei/bot/tg.Bot.onMessage(0xc000438280, 0x2acea69f, 0xc000779a38, 0x8, 0x0, 0x0, 0xc000779a50, 0xd, 0x0, 0x0, ...)
zwei_1      |   /home/app/bot/tg/bot.go:30 +0x2af
zwei_1      | github.com/jqs7/zwei/bot/tg.Bot.processUpdate(0xc000438280, 0x2acea69f, 0xc000779a38, 0x8, 0x0, 0x0, 0xc000779a50, 0xd, 0x0, 0x0, ...)
zwei_1      |   /home/app/bot/tg/bot.go:17 +0x11b
zwei_1      | github.com/jqs7/zwei/bot/tg.Bot.Run(0xc000438280, 0x2acea69f, 0xc000779a38, 0x8, 0x0, 0x0, 0xc000779a50, 0xd, 0x0, 0x0, ...)
zwei_1      |   /home/app/bot/tg/tg.go:60 +0x11a
zwei_1      | main.main()
```

**Comment by jqs7** [comment]
> 应该是 font文件没加进去
> checking
> #3

是的，需要修改下 `Dockerfile`，将 fonts 目录放进去

**Comment by llitfkitfk** [comment]
验证码图片那个库 还需要cgo

**Comment by jqs7** [comment]
扶额 [hanguofeng/freetype-go-mirror](https://github.com/hanguofeng/freetype-go-mirror) 这个依赖需要 CGO

**Comment by jqs7** [comment]
> 应该是 font文件没加进去
> checking
> #3

对了，还有在运行 migration 的时候，`idiom.json` 也要放到工作目录下

**Comment by llitfkitfk** [comment]
fixed in #5
